service: scraping-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-west-2

functions:
  hello__fun:
    handler: src/common/handler.hello__fun
    timeout: 5
    description: Say Hi
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
        - "!venv/**"
plugins:
  - serverless-python-requirements

package:
  individually: true
